integration:
  parallel_risks:
      safe_threshold: 1.3
      warning_threshold: 1.6
  target_days: 30
  steps:
    step1: 3
    step2: 7
    step3: 5
    step4: 5
    step5: 1
    step6: 8
    step7: 1
  
thresholds:
  yellow_multiplier: 1.2
  red_multiplier: 1.5

factors:
  weights:
    data_volume: 0.4
    api_complexity: 0.4
    data_quality: 0.2

probability:
  trend_weight: 0.3
  complexity_weight: 0.4
  correlation_weight: 0.3

